# This function takes original peak file and a list of annotation files which are
# generated by intersecting with region files
# Output a TAB separated file where annotation result is added as columns

library(optparse)
library(dplyr)
library(stringr)

# functions
buildPeakID <- function(data.tb) {
  data.tb <- data.tb %>% 
    mutate(peak.id = paste(V1, V2, V3, V4, V10, V11, V12))
  return(data.tb)
}
buildMatchID <- function(data.tb) {
  data.tb <- data.tb %>% 
    mutate(match.id = paste(V1, V2, V3, V4, V10, V11, V12, transcript_id))
  return(data.tb)
}
splitByComma <- function(string) {
  return(strsplit(string, ',')[[1]])
}
computeSize <- function(string) {
  sizes <- splitByComma(string)
  class(sizes) <- 'numeric'
  return(sum(sizes))
}

option_list = list(
  make_option(c("-p", "--peak"), type = "character", default = NULL,
              help = "Peak file", metavar = "character"),
	make_option(c("-a", "--annotations"), type = "character", default = NULL,
              help = "A list of annotation file names separated by comma", 
	            metavar = "character"),
  make_option(c("-an", "--annotation_names"), type = "character", default = NULL,
              help = "A list of annotation names used for output table 
                      (separated by comma). Use the same order as --annotations", 
              metavar = "character"),
  make_option(c("-o", "--output"), type = "character", default = NULL,
              help = "Output file name", metavar = "character")
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

peak.in <- opt$peak  # '../../test/test_peak.bed'
annotation.in <- opt$annotations  # 'temp/CDS__test.bed.gz,temp/exon__test.bed.gz'
annotation.name.in <- opt$annotation_names  # 'CDS,exon'
annotation.in <- splitByComma(annotation.in)
if(is.character(annotation.name.in)) {
  annotation.name.in <- splitByComma(annotation.name.in)
}
stopifnot(length(annotation.in) == length(annotation.name.in))

peak <- read.table(peak.in, header = F, sep = '\t', skip = 1)
peak <- buildPeakID(peak)
peak$size <- sapply(as.character(peak$V11), computeSize)




for(i in 1 : length(annotation.in)) {
  anno <- read.table(annotation.in[i], sep = '\t', header = F)
  anno$transcript_id <- str_match(anno$V21, 
                                  pattern = 'gene_id [a-zA-Z0-9-_.]+; transcript_id ([A-Z_0-9-._]+); exon_number')[, 2]
  anno <- buildMatchID(anno)
  anno <- buildPeakID(anno)
  anno <- anno %>%
    group_by(match.id, peak.id) %>%
    summarise(match.size = sum(V22)) %>%
    ungroup()
  anno <- anno %>%
    group_by(peak.id) %>%
    summarise(size = max(match.size)) %>%
    ungroup()
  anno.idx <- match(anno$peak.id, peak$peak.id)
  if(is.null(annotation.name.in)) {
    anno.colname <- annotation.in[i]
  } else {
    anno.colname <- annotation.name.in[i]
  }
  peak[[anno.colname]] <- rep(0, nrow(peak))
  peak[ anno.idx, anno.colname] <- anno$size
}

gz <- gzfile(opt$output, 'w')
write.table(x = peak, file = gz, 
            col.names = T, row.names = F, quote = F, sep = '\t')
close(gz)
