# This function takes original peak file and a list of annotation files which are
# generated by intersecting with region files
# Output a TAB separated file where annotation result is added as columns

library("optparse")

option_list = list(
  make_option(c("-p", "--peak"), type = "character", default = NULL,
              help = "Peak file", metavar = "character"),
	make_option(c("-a", "--annotations"), type = "character", default = NULL,
              help = "A list of annotation file names separated by comma", 
	            metavar = "character"),
  make_option(c("-o", "--output"), type = "character", default = NULL,
              help = "Output file name", metavar = "character")
);

opt_parser <- OptionParser(option_list=option_list)
opt <- parse_args(opt_parser)


